---
- name: Verify Rancher GUI Accessibility
  hosts: localhost
  gather_facts: false
    #  vars:
    # Fallback for testing; replace or define in your host vars
    # kube_vip_address: "192.168.1.187" 

  tasks:
    - name: Wait for Rancher GUI to become responsive
      ansible.builtin.shell: |
        curl -kIv -s -o /dev/null -w "%{http_code}"  -H "Host: {{ rancher_hostname }}" https://{{ kube_vip_address }}/dashboard/auth/login
      register: curl_check
      # Safely check if stdout exists before reading its value
      until: >
        curl_check.stdout is defined and 
        (curl_check.stdout == "200" or curl_check.stdout == "302")
      retries: 2
      delay: 10
      delegate_to: localhost
      changed_when: false
    
    - name: Confirm successful connection
      ansible.builtin.debug:
        msg: "Success! Rancher GUI is accessible at https://{{ kube_vip_address }}"

