---
- name: Fetch and Patch K3s Kubeconfig
  hosts: minipaf_masters[0]
  tasks:
    - name: Store the first master IP address
      ansible.builtin.set_fact:
        the_first_master: "{{ hostvars[groups['minipaf_masters'][0]]['ansible_host'] }}"
      run_once: true

    - name: Fetch the kubeconfig file from the master node
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env', 'HOME') }}/.kube/config_minipaf"
        flat: yes
      become: true

    - name: Replace localhost IP with Kube-VIP address on local machine
      ansible.builtin.replace:
        path: "{{ lookup('env', 'HOME') }}/.kube/config_minipaf"
        regexp: 'https://127.0.0.1:6443'
        replace: "https://{{ the_first_master }}:6443"
      delegate_to: localhost

    - name: Set secure permissions on local kubeconfig
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.kube/config_minipaf"
        mode: '0600'
      delegate_to: localhost

# the_first_host: "{{ hostvars[groups['minipaf_masters'][0]]['ansible_host'] }}
