---
- name: Fetch and Patch K3s Kubeconfig
  hosts: first_master
  tasks:
    - name: Fetch the kubeconfig file from the master node
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env', 'HOME') }}/.kube/config_sense-k3s"
        flat: yes
      become: true

    - name: Replace localhost IP with Kube-VIP address on local machine
      ansible.builtin.replace:
        path: "{{ lookup('env', 'HOME') }}/.kube/config_sense-k3s"
        regexp: 'https://127.0.0.1:6443'
        replace: "https://{{ kube_vip_address }}:6443"
      delegate_to: localhost

    - name: Set secure permissions on local kubeconfig
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.kube/config_sense-k3s"
        mode: '0600'
      delegate_to: localhost

