[first_master]
172.18.29.30 ansible_user=piperov

[additional_masters]
172.18.29.31 ansible_user=piperov
172.18.29.32 ansible_user=piperov

[k3s_cluster:children]
first_master
additional_masters

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
