[first_master]
192.168.1.184  ansible_user=piperov

[additional_masters]
192.168.1.185 ansible_user=piperov
192.168.1.186 ansible_user=piperov

[k3s_cluster:children]
first_master
additional_masters

[k3s_cluster:vars]
# --- TOGGLE Kube-VIP IP and FQDN here ---
# kube_vip_address="172.18.29.29"
# kube_vip_fqdn="sense-k3s.cms.rcac.purdue.edu"
kube_vip_address="192.168.1.187"
kube_vip_fqdn="sense-k3s.internal"

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
# --- TOGGLE RANCHER HOSTNAME ---
# rancher_hostname="sense-k3s.cms.rcac.purdue.edu"
rancher_hostname="sense-k3s.internal"
