---
- name: Verify local K3s service health
  ansible.builtin.systemd:
    name: k3s
  register: k3s_service

- name: Identify active Kube-VIP node
  ansible.builtin.command:
    cmd: crictl ps --name kube-vip -q
  register: kubevip_container
  changed_when: false
  ignore_errors: true

- name: Report Kube-VIP role
  ansible.builtin.debug:
    msg: >
      {{ 'Kube-VIP is ACTIVE on this host' if kubevip_container.rc == 0 and kubevip_container.stdout != '' else 'Kube-VIP is in STANDBY mode' }}

