---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ssl-hep
  namespace: servicex
spec:
  interval: 2h
  url: "https://ssl-hep.github.io/ssl-helm-charts/"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex
  namespace: minipaf
spec:
  releaseName: servicex
  interval: 5m
  chart:
    spec:
      chart: servicex
      version: v1.8.3
      sourceRef:
        kind: HelmRepository
        name: ssl-hep
        namespace: flux-system
      interval: 1m
  values:
    # Instruct the chart to pull credentials from a dedicated secret
    gridCertSecret: "grid-certs-secret"
    # Basic sizing configuration matching readthedocs guidelines
    replicas: 1

    # --- Infrastructure & Global Configurations ---
    postgres:
      enabled: true
    objectStore:
      publicURL: localhost:9000
    gridAccount: piperov

    # --- Code Generator Block ---
    codeGen:
      uproot-raw:
        enabled: true
        image: sslhep/servicex_code_gen_raw_uproot
        tag: "v1.8.3"
      defaultScienceContainerImage: sslhep/servicex_science_image_combined_root
      defaultScienceContainerTag: 5.7.2-6.38.04
      compressionAlgorithm: ZSTD
      compressionLevel: 0
      atlasr21:
        enabled: false
      atlasr22:
        enabled: false
      atlasr25:
        enabled: false
      topcp:
        enabled: false

    # --- Dataset ID (DID) Finder Blocks ---
    didFinder:
      rucio:
        enabled: false
        rucio_host: http://cms-rucio.cern.ch
        auth_host: https://cms-rucio-auth.cern.ch

        threads: 2
        site: T2_US_Purdue
      CERNOpenData:
        enabled: true
        pullPolicy: Always
      xrootd:
        enabled: true
        image: sslhep/servicex-did-finder-xrootd
        tag: "v1.8.3"
      atlasopenmagic:
        enabled: false
      x509Secrets:
        vomsOrg: cms

